task 2 resolution
js-tasks-ru/js-20220909_dagolubev pull request #2
Opened 2022-09-17 18:22 UTC by craftgoldman

2022-09-17 18:23 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-18 16:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-19 13:10 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let order = (param == 'asc') ? 1 : (param == 'desc') ? -1 : undefined;
- `const order`
- нет такого оператора `==` в JS
- мы не возвращаем `undefined` напрямую

2022-09-19 13:11 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let object = {};
`const object`

2022-09-19 13:11 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    for (let prop of fields) {
`const prop`

2022-09-19 13:12 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        if (prop in obj) {
а где проверка `hasOwn`?
что выведет такой вызов?
```
pick({}, 'toString')
```

2022-09-19 13:12 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    let object = {};
`const`

2022-09-19 13:12 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-19 17:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-19 20:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-20 19:03 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-22 21:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-23 10:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    const order = (param === 'asc') ? 1 : (param === 'desc') ? -1 : 0;
не используйте такие тернарники, они очень сложно читаются

2022-09-23 10:26 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        if (prop in obj && obj.hasOwnProperty(prop) ) {
пожалуйста используйте `Object.hasOwn`, проверка `in` не нужна

2022-09-23 10:26 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    for (let [prop, value] of Object.entries(obj)) {
`const`

2022-09-23 10:26 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const pathKeys = path.split('.');
good 👍 лайк за замыкание

2022-09-23 10:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return function (object = undefined) {
нет необходимости приcваивать `undefined` в качестве значения по умолчанию, по умолчанию там и так будет `undefined`

2022-09-23 10:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +            if (obj != undefined) {
`!=` нет такого оператора в JS

2022-09-23 10:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +                if (rest.length == 0) {
`==` и такого нет

2022-09-23 10:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +                    return getValue(obj[prop], rest);
👍 good  лайк за рекурсию

2022-09-23 10:28 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +export function invertObj(obj = undefined) {
так делать нельзя! `obj = undefined`

2022-09-23 10:28 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    if (obj != undefined) {
нет такого оператора

2022-09-23 10:28 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +    for (const s of string) {
не экономьте на именах переменных!

2022-09-23 10:29 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +    return [... new Set(arr)];
👍 good

2022-09-23 10:29 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.list   = params.data ?? [];
почему используется `??` а не `||`?

2022-09-23 10:29 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        if (this.value == undefined) return '';
нет такого оператора `==`

2022-09-23 10:30 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        return (typeof this.format == 'function') ? this.format(this.value) : this.value;
может стоит присвоить this.format значение по умолчанию, чтобы избавится от этой проверки?

2022-09-23 10:30 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    getTemplate() {
👍 good

2022-09-23 10:30 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    render() {
👍 good

2022-09-23 10:31 UTC, dosandk requested changes
внести правки:
- не использовать операторы `==` и `!=`
- не задавать значение `undefined` в качестве значения по умолчанию
- проверить использование `let` и `const`

2022-09-23 15:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-26 11:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-26 12:12 UTC, dosandk submitted a review, later dismissed
good 👍

2022-09-26 12:12 UTC, jsru commented
К сожалению, PR не может быть замержен, dosandk вероятно сможет помочь.

2022-09-26 12:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-27 09:04 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
good 👍

2022-09-27 09:04 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +
good 👍

2022-09-27 09:05 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    const object = {};
good 👍

2022-09-27 09:05 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    if (obj !== undefined) {
good 👍

2022-09-27 09:05 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +export function trimSymbols(string, size = undefined) {
good 👍

2022-09-27 09:05 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    constructor(params = {}) {
good 👍

2022-09-27 09:05 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        if (this.value === undefined) return '';
тут лучше подойдет тернарное выражение

2022-09-27 09:06 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        return (this.link !== undefined) ? `<a href="${this.link}" class="column-chart__link">View all</a>`: '';
можно сокращать проверку:
```
this.link ? <condition 1> : <condition 2>
```

2022-09-27 09:06 UTC, dosandk approved these changes
good 👍

2022-09-27 09:07 UTC, merged